Spool RyanEggert-Exam1.txt

--SET ECHO ON
SET SERVEROUTPUT ON;
CLEAR SCR

DROP TABLE Exam1_Invoice;
DROP TABLE Exam1_Customer;

--Question 1
CREATE TABLE Exam1_Customer (
	Cust_Num	INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1),
	Cust_LName	VARCHAR (20) NOT NULL,
	Cust_FName	VARCHAR (20) NOT NULL,
	Cust_Balance	Number (8,2) NOT NULL,
	EmailAddress	VARCHAR (50) NULL,
CONSTRAINT Cust_Num_PK PRIMARY KEY (Cust_Num)
);

DESCRIBE Exam1_Customer;

--Question 2
CREATE TABLE Exam1_Invoice (
	Inv_Num		INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 8000 INCREMENT BY 1),
	Cust_Num	INTEGER NOT NULL,
	Inv_Date	DATE,
	Inv_Amount	NUMBER (8,2),
CONSTRAINT Inv_Num_PK PRIMARY KEY (Inv_Num),
CONSTRAINT Cust_Num_FK FOREIGN KEY (Cust_Num) REFERENCES Exam1_Customer (Cust_Num)
);

DESCRIBE Exam1_Invoice;

--Question 3

INSERT INTO Exam1_Customer VALUES(
	DEFAULT, 'Smith', 'Jeanne', '1050.11', '');
INSERT INTO Exam1_Customer VALUES(
	DEFAULT, 'Ortega', 'Juan', '840.92', '');
INSERT INTO Exam1_Customer VALUES(
	DEFAULT, 'McPherson', 'Anne', '956.45', '');
INSERT INTO Exam1_Customer VALUES(
	DEFAULT, 'Ortega', 'Juan', '437.25', '');
INSERT INTO Exam1_Customer VALUES(
	DEFAULT, 'Kowalski', 'Juan', '63375', '');
INSERT INTO Exam1_Customer VALUES(
	DEFAULT, 'Chen', 'George', '331.35', '');
SELECT * FROM Exam1_Customer;

--Question 4

INSERT INTO Exam1_Invoice VALUES(
	DEFAULT, '1000', '23-APR-14', '235.89');
INSERT INTO Exam1_Invoice VALUES(
	DEFAULT, '1001', '23-MAR-14', '312.82');
INSERT INTO Exam1_Invoice VALUES(
	DEFAULT, '1001', '30-MAR-14', '528.1');
INSERT INTO Exam1_Invoice VALUES(
	DEFAULT, '1000', '12-APR-14', '194.78');
INSERT INTO Exam1_Invoice VALUES(
	DEFAULT, '1000', '23-APR-14', '619.44');
SELECT * FROM Exam1_Invoice;

--Question 5

CREATE OR REPLACE VIEW Question5 AS
SELECT Inv_Num, Inv_Amount, AVG(Inv_Amount) AS Average_Amount, (AVG(Inv_Amount))-Inv_Amount AS Invoice_Difference
FROM Exam1_Invoice
GROUP BY Inv_Num, Inv_Amount;

SELECT * FROM Question5;

--Question 6

DESCRIBE Exam1_Customer;

ALTER TABLE Exam1_Customer
	ADD USERNAME VARCHAR(25);
ALTER TABLE Exam1_Customer
	ADD CUST_DOB DATE;

DESCRIBE Exam1_Customer;

--Question 7

SELECT * FROM Exam1_Customer;

UPDATE Exam1_Customer
SET CUST_DOB = '15-MAR-00'
WHERE Cust_Num = '1000';

UPDATE Exam1_Customer
SET CUST_DOB = '22-DEC-98'
WHERE Cust_Num = '1001';

SELECT * FROM Exam1_Customer;

--Question 8

CREATE OR REPLACE PROCEDURE prc_cust_add (
 --p_Cust_Num IN Exam1_Customer.Cust_Num%TYPE,
 p_Cust_LName IN Exam1_Customer.Cust_LName%TYPE,
 p_Cust_FName IN Exam1_Customer.Cust_FName%TYPE,
 p_Cust_Balance IN Exam1_Customer.Cust_Balance%TYPE,
 p_EmailAddress IN Exam1_Customer.EmailAddress%TYPE)
IS
BEGIN
INSERT INTO Exam1_Customer(Cust_LName, Cust_FName, Cust_Balance, EmailAddress)
VALUES(p_Cust_LName, p_Cust_FName, p_Cust_Balance, p_EmailAddress);
IF SQL%NOTFOUND THEN
 RAISE_APPLICATION_ERROR(-030518, 'No Customer Able to Update');
END IF;
END;
/
EXECUTE prc_cust_add('Jolie', 'Anglina', '0.00', '')
SELECT * FROM Exam1_Customer;

--Question 9
/*
CREATE OR REPLACE VIEW view_Customer_Sales AS
SELECT Exam1_Customer.Cust_Num, (Cust_LName || ' ' || Cust_FName) AS CustomerName, USERNAME, Inv_Num, Inv_Date
FROM Exam1_Customer, Exam1_Invoice;

SELECT * FROM view_Customer_Sales;
*/

SET SERVEROUTPUT OFF;
--ECHO OFF;
SPOOL OFF